config/routes.rb
Optidemo::Application.routes.draw do
  match 'sass' => 'slideshow#sass'
  match 'compass' => 'slideshow#compass'
  match 'optimization' => 'slideshow#optimization'
  match 'reference' => 'home#reference'
  root :to => 'home#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
  
  def references
  end
  
end

app/controllers/slideshow_controller.rb
class SlideshowController < ApplicationController
  layout "slideshows"
  
  def sass
  end

  def compass
  end

  def optimization
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def stylesheets *sheets
    if sheets.empty?
      @stylesheets || %w(application)
    else
      @stylesheets = sheets
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/slideshow_helper.rb
module SlideshowHelper
end

app/views/home/index.html.erb
<%= render partial: "shared/header" %>
<%= render partial: "shared/slider" %>

<div class="clear"></div>
 <!-- Main Section -->
<div id="content" class="shadow">
  <div class="container_12 testimonials">
  <span class="testimonial-message">&ldquo;Anybody who’s built a website of any size knows how quickly CSS can get out of hand. Style sheets can grow bloated and lengthy, 
    making it difficult to find things, introducing redundancy and producing an end product that makes code maintenance tedious. 
    Let’s face it — CSS is not very well-designed.&rdquo;</span> - <%= link_to("Mashable", "http://mashable.com/2011/06/14/compass-css-guide/") %>
  </div>
  <div class="clear"></div>
  <div class="container_12">
    <div class="grid_6"><h1>Sass</h1>
    <p>Sass is a meta-language on top of CSS that’s used to describe the style of a document cleanly and structurally, with more power than flat CSS allows. 
      Sass both provides a simpler, more elegant syntax for CSS and implements various features that are useful for creating manageable stylesheets.</p>
    </div>
    <div class="grid_6"><h1>Compass</h1>
    <p>Compass is an open-source CSS Authoring Framework. Sass is an extension of CSS3 which adds nested rules, variables, mixins, selector inheritance, and more. 
      Sass generates well formatted CSS and makes your stylesheets easier to organize and maintain.</p>
    </div>
  </div>
  <div class="clear"></div>
</div>
 <!-- End of Main Section -->
 
<%= render partial: "shared/footer" %>

app/views/home/reference.html.erb
<%= render partial: "shared/header" %>

<!-- Main Section -->
<div class="main-section">
  <div class="container_12 ">
    <div class="grid_9">
    <h1>Videos on Sass</h1>
    <p>
      <iframe width="420" height="315" src="http://www.youtube.com/embed/opj1hV2b3gA" frameborder="0" allowfullscreen></iframe>
    </p>
    
    <h1>Videos on Compass</h1>
    <p>
      <iframe src="http://player.vimeo.com/video/4335944?title=0&amp;byline=0&amp;portrait=0" width="400" height="225" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe><p><a href="http://vimeo.com/4335944">Compass: A Real Stylesheet Framework</a> from <a href="http://vimeo.com/user1651762">Chris Eppstein</a> on <a href="http://vimeo.com">Vimeo</a>.</p>
    </p>
    </div>

    <div id="sidebar" class="grid_3">
      <p>Links with helpful resources.</p>
      <h1>Sass</h1>
      <ul>
        <li><a href="http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html">Sass Refference</a></li>
        <li><a href="http://thesassway.com/">The Sass Way</a></li>
      </ul>

      <h1>Compass</h1>
      <ul>
        <li><a href="http://compass-style.org/">Compass</a></li>
        <li><a href="http://railscasts.com/episodes/334-compass-css-sprites">Railscasts: #334 Compass & CSS Sprites</a></li>
      </ul>
      
      <h1>Image Compression</h1>
      <ul>
        <li><a href="http://imageoptim.com/">ImageOptim</a></li>
        <li><a href="http://pngnq.sourceforge.net/">Pngnq</a></li>
        <li><a href="http://compass-style.org/reference/compass/helpers/inline-data/">Compass Inline Data Helpers</a></li>
      </ul>
    </div>
  <div class="clear"></div>
  </div>
</div>
<!-- End of Main Section -->

<%= render partial: "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Optidemo</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/layouts/slideshows.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Optidemo</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    "slideshow", :media => "all" %>
  <%= javascript_include_tag "slideshow" %>
  <%= csrf_meta_tags %>
</head>
<body data-duration="85">
<%= yield %>
</body>
</html>

app/views/shared/_footer.html.erb
<div class="clear"></div>
<div id="tail">
  <div class="container_12">
    Optidemo - An asset optimization 101 &bull; Developed by <%= link_to("Mike", "http://twitter.com/emikebr") %> &bull; 2012
  </div>
</div>
<script type="text/javascript"> Cufon.now(); </script>

app/views/shared/_header.html.erb
<!-- Header -->
<div class="container_12">
  <div id="header" class="grid_12">
    <div id="logo" class="grid_4 alpha"><%= link_to(image_tag("logo.png"), root_path)%></div>
    <div id="menu" class="grid_8 omega">
      <ul id="nav">
        <li><%= link_to "Sass", sass_path %></li>
        <li><%= link_to "Compass", compass_path %></li>
        <li><%= link_to "Asset Optimization", optimization_path %></li>
        <li class="last"><%= link_to "References", reference_path %></li>
      </ul>
    </div>                
  </div>
  <div class="clear"></div>
</div>
<!-- End of Header -->

app/views/shared/_slider.html.erb
<!-- Image Slider -->
<div class="container_12">
  <div id="slider" class="grid_12">
    <div class="slides_container">
      <div class="slide">
        <%= image_tag("assets101.png") %>
      </div>
      <div class="slide">
        <%= image_tag("sass.png") %>
      </div>
      <div class="slide">
        <%= image_tag("compass.png") %>
      </div>
      <div class="slide">
        <%= image_tag("base64.png") %>
      </div>
    </div>
    <a href="#" class="prev"><%= image_tag("arrow-prev.png", :alt => "Arrow Prev", :width => 24, :height => 43) %></a>
    <a href="#" class="next"><%= image_tag("arrow-next.png", :alt => "Arrow Next", :width => 24, :height => 43) %></a>
  </div>
  <div class="clear"></div>
</div>
<!-- End of Slider -->

app/views/shared/_slideshow-js.html.erb
<script src="assets/lib/keynote_slideshow.js"></script>
<script>var slideshow = new SlideShow();</script>

app/views/slideshow/compass.html.erb
<%= render partial: "shared/header" %>
<div class="clear"></div>
 <!-- Main Section -->
<div id="content">
  <div class="container_12">
    <section id="intro" class="slide">
    	<h1 class="compass">Compass 101</h1>
    	<p class="attribution">By Mike .V - @emikebr</p>
    </section>

    <section>
    	<header class="slide">
    		<h1>Compass 101</h1>
    	</header>

    	<section class="slide">
    		<h2>What is Compass?</h2>
    		<p class="delayed">Compass is an open source CSS authoring framework written in Ruby that attempts to fix a lot of the shortcomings of CSS. It also streamlines development by providing a number of utilities and tools to make writing your CSS files easier and faster.</p>
    		<p class="delayed">And most important...</p>
    		<p class="delayed">Compass uses Sass!</p>
    	</section>
    
    	<section class="slide">
    		<h2>Why Compass?</h2>
    		<ul>
    		  <li class="delayed">Experience cleaner markup without presentational classes.</li>
    		  <li class="delayed">It’s chock full of the web’s best reusable patterns.</li>
    		  <li class="delayed">It makes creating sprites a breeze.</li>
    		  <li class="delayed">Supports Inline Data through base64. - More on this in Asset Optimization.</li>
    		  <li class="delayed">Compass mixins make CSS3 easy. - No need to worry about vendor prefixes.</li>
    		  <li class="delayed">Create beautiful typographic rhythms.</li>
    		  <li class="delayed">You can create your own Compass extensions.</li>
    		</ul>
    	</section>
    	
    	<section class="slide">
    		<h2>How Does COMPASS Work?</h2>
    		<p>Now that we’ve gone over what COMPASS is and discussed a few of its features, let’s take a look at some of them in action.</p>
    	</section>
    
    	<section class="slide">
    		<h2>Compass CSS3</h2>
    		<p>SCSS</p>
    		<pre>
@import "compass/css3";
.box { 
  @include border-radius(8px); 
  @include background (linear-gradient(#000, #333));
}.
    		</pre>
    	</section>
    	
    	<section class="slide">
    		<h2>CSS3</h2>
    		<p>CSS</p>
    		<pre>
.box { 
  -moz-border-radius: 8px; 
  -webkit-border-radius: 8px; 
  -ms-border-radius: 8px; 
  border-radius: 8px; 
  background: -webkit-gradient(linear, 50% 0%, 50% 100%,color-stop(0%, #000000), color-stop(100%, #333333)); 
  background: -webkit-linear-gradient(#000000, #333333); 
  […] // Vender prefixes omitted to save space, but you get the idea. - Mike
  background: linear-gradient(#000000, #333333);
}
    		</pre>
    	</section>
    	
    	<section class="slide">
    		<h2>Image Dimension Helpers</h2>
    		<p>SCSS</p>
    		<pre>
@import "compass";
$image: "logo.jpg";
header { 
  background: image-url($image); 
  h1 { 
    width: image-width($image); 
    height: image-height($image); 
  }
}
    		</pre>
    	</section>

    	<section class="slide">
    		<h2>Image Dimension Helpers</h2>
    		<p>CSS</p>
    		<pre>
header { 
  background: url(/assets/logo-92abef214666bab574edece3.jpg);
}
header h1 { 
  width: 346px; 
  height: 400px;
}
    		</pre>
    	</section>
    	
    	<section class="slide">
    		<h2>Spriting with Compass</h2>
    		<p>Spriting has never been easier with Compass. You place the sprite images in a folder, import them into your stylesheet, and then you can use the sprite in your selectors in one of several convenient ways.</p>
    	</section>

    	<section class="slide">
    		<h2>Spriting with Compass</h2>
    		<p>So let's imagine that in your project's image folder there are these icons:</p>
        <code>assets/images/social/fb.png</code><br />
        <code>assets/images/social/twitter.png</code><br />
        <code>assets/images/social/LinkedIn.png</code><br />
        <code>assets/images/social/gplus.png</code><br />
        <code>assets/images/social/email.png</code><br />
        <code>assets/images/social/rss.png</code>
        <p>Each is an icon that is 32px square.</p>
    	</section>
    	
    	<section class="slide">
    		<h2>Spriting with Compass</h2>
    		<p>SCSS</p>
    		<pre>
@import "compass";
@import "social/*.png";
@include all-social-sprites($dimensions:true); 
    		</pre>
    	</section>

    	<section class="slide">
    		<h2>Spriting with Compass</h2>
    		<p>CSS</p>
    		<pre>
.social-sprite, .social-fb, .social-twitter, .social-LinkedIn, etc... {
  background: url(/assets/social-92abef214666bab574edece3.png); no-repeat;
}
.social-fb { 
  background-position: 0 0; 
  height: 32px; 
  width: 32px;
}
.social-twitter { 
  background-position: -15px 0; 
  height: 32px; 
  width: 32px;
}
    		</pre>
    	</section>
  	
    </section>
  

    <section class="slide">
    	<h2>last but not least...</h2>
    	<p>To really get into Sass and Compass I recommend you take a look at Pragmatic Guide to Sass.</p>
    	<%= image_tag("pragmatic-Guide-to-Sass.jpg") %>
    </section>
  </div>
  <div class="clear"></div>
</div>
 <!-- End of Main Section -->

<%= render partial: "shared/slideshow-js" %>

app/views/slideshow/optimization.html.erb
<%= render partial: "shared/header" %>
<div class="clear"></div>
 <!-- Main Section -->
<div id="content">
  <div class="container_12">
    <section id="intro" class="slide">
    	<h1 class="base64">Image Optimization and base64 101</h1>
    	<p class="attribution">By Mike .V - @emikebr</p>
    </section>

    <section>
    	<header class="slide">
    		<h1>Image Compression</h1>
    	</header>

    	<section class="slide">
    		<h2>Optimizing Images</h2>
    		<p>All imaging software —and especially Adobe Photoshop/Fireworks— output inefficient JPEG and PNG files that waste sometimes even hundreds of kilobytes in needless information. There are a number of tools out there that can losslessly reduce the file size.</p>
    		<p>Let's talk about what we have available to help us compress images and optimize for the web.</p>
    	</section>
    	
    	<section class="slide">
    		<h2>ImageOptim</h2>
    		<p>ImageOptim combines multiple PNG (JPEG and Gif) optimization tools into a simple drag-and-drop interface. Everything it does is lossless, based on optimizing the PNG compression parameters and removing excess hidden data (such as EXIF in JPEGs).</p>
    		<p>Let's talk about what we have available to help us compress images and optimize for the web.</p>
    		<%= image_tag("image-optim.png") %>
    		<p class="delayed">An excellent 55% bandwidth savings and all you had to do was drag-and-drop! Good tool for non-programers. A.k.a. Designers! Hahaha!</p>
    	</section>
    	
    	<section class="slide">
    		<h2>PNGNQ</h2>
    		<p>If you are feeling extra geeky, then pngnq (http://pngnq.sourceforge.net/) is a command line tool that quantizes 24/32-bit PNG files into near-perfect 8-bit PNGs. The results are stunning. It also maintains full alpha transparency, perfect for website graphics! Website graphics are not usually going to be using as many colors as a photograph so pngnq is perfect for being extra brutal with saving bytes.</p><br />
    		
    		<p>Go to http://pngnq.sourceforge.net/pngnqsamples.html to see some examples.</p>
    	</section>
    	
    	<section class="slide">
    		<h2>Reducing HTTP-Requests</h2>
    		<p>Bandwidth is not the problem when it comes to speed, even on dial-up. The browser can only do a limited number of simultaneous HTTP requests (usually between 2 and 6). That is the bottleneck that you are fighting against.</p><br />
    		
    		<p>By reducing the number of HTTP-requests down to an absolute minimum, you will make the Round-trip time (RTT) almost instantaneous.</p>
    	</section>
    	
    	<section class="slide">
    		<h2>Reducing HTTP-Requests</h2>
    		<p class="delayed">Bandwidth is not the problem when it comes to speed, even on dial-up. The browser can only do a limited number of simultaneous HTTP requests (usually between 2 and 6). That is the bottleneck that you are fighting against.</p>
    		
    		<p class="delayed">By reducing the number of HTTP-requests down to an absolute minimum, you will make the Round-trip time (RTT) almost instantaneous.</p>
    		
    		<p class="delayed">Think of it this way: in a worst case scenario, a single HTTP-request could take up to a second alone if the server is under heavy load or if the bandwidth is already saturated.</p>
    	</section>
    	
    	<section class="slide">
    		<h2>In Rails...</h2>
    		<p class="delayed">...we have the Asset Pipeline which provides a framework to concatenate and minify or compress JavaScript and CSS assets. It also adds the ability to write these assets in other languages such as CoffeeScript, Sass and ERB.</p>
    	</section>
    	
    	<section class="slide">
    		<h2>Well, what about images?</h2>
    		<p class="delayed">In the Compass section we learnt how to create sprites with ease out of several images.</p>
    		<p class="delayed">You can gain image performance by optimizing the images you want to add to the Compass Sprite beforehand.</p>
    	</section>
    	
    	<section class="slide">
    		<h2>Base-64 Encoded Images</h2>
    		<p class="delayed">The Problem <br />Round-trip time (RTT) is the time it takes for a client to send a request and the server to send a response over the network, not including the time required for data transfer. That is, it includes the back-and-forth time on the wire, but excludes the time to fully download the transferred bytes (and is therefore unrelated to bandwidth). Many web pages require dozens of RTTs - each included css, javascript or image file needs 1 RTT for HTTP request.</p>
    		<p class="delayed">RTTs vary from less than one millisecond on a LAN to over one second in the worst cases. For small download file sizes (e.g. rounded corner image used as background in css) RTT is the major contributing factor to latency on "fast" (broadband) connections. Therefore, an important strategy for speeding up web page performance is to minimize the number of round trips that need to be made. Since the majority of those round trips consist of HTTP requests and responses, it's especially important to minimize the number of requests that the client needs to make and to parallelize them as much as possible.</p>
    	</section>
    	
    	<section class="slide">
    		<h2>Enter Base-64 FTW!</h2>
    		<p>Fortunately and awesomely Compass provides us with Inline Data Helpers.</p>
    		<p class="delayed">With Compass we can tackle this like so:</p>
    		<p class="delayed">SCSS</p>
    		<pre class="delayed">
$image: "some-image.png";
.someClass { background: inline-image($image);
}
    		</pre>
    		<p class="delayed">This Embeds the contents of an image directly inside your stylesheet, eliminating the need for another HTTP request.</p>
    	</section>
    	
    	<section class="slide">
    		<h2>Enter Base-64 FTW!</h2>
    		<p>CSS</p>
    		<pre>
.someClass { background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAABkCAMAAACxdeD+AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccl
  0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/CSSIiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1
  sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4
  gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIge
  G1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9
  Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNSBNYWNpbnRvc2gi
  IHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6ODVBQkU5NzQ1NjU1MTFFMUFGODdFNTI1QzQwQzYzNkMiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6ODVBQkU5NzU1NjU
  1MTFFMUFGODdFNTI1QzQwQzYzNkMiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDowQjAyREI0RDU2NEUxMUUxQUY4N0U1MjVDNDBDNjM2
  QyIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDowQjAyREI0RTU2NEUxMUUxQUY4N0U1MjVDNDBDNjM2QyIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6e
  G1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pvv5YQwAAACEUExURcvLy/Pz87CwsImJic/Pz/v7++Tk5K+vr62trd3d3YCAgLGxsaKiot/f38rKyri4uPf398fHx/Dw8Pj4+LW1
  tenp6ZaWlqurq66uroODg8jIyIuLi5ycnIqKiu/v7/r6+oWFhZubm9jY2KampuHh4ZiYmNLS0tnZ2YSEhH9/f7Kysv///3IN8QsAAACqSURBVHja7NXnDoIwFAXgikXcey/cem7f//
  2sDV3E8EdRY3qTNvTLpaeEEJh4Uizgn2L/clxucziZAlgdPIzXaA8SbIYu1nCOhZiDuXhFIuduk1xsIHr0L2YKO0zVGHueihNxhXXoulXMOSOD1XLRpu8s8hZl1Rv9+tuUh3yls4zb
  P7bnd4NC+vvSySAZVGs76U55rYfdU3+v5AXlLEv3rfiJKPw7CvAuwAAQmUbpoWRiDAAAAABJRU5ErkJggg==);
}
    		</pre>
    		<p>The image is embeded directly inside your stylesheet, eliminating the need for another HTTP request.</p>
    	</section>
    	
    	<section class="slide">
    		<h2>Not using Compass?</h2>
    		<p class="delayed">The asset pipeline automatically evaluates ERB. This means that if you add an erb extension to a CSS asset (for example, application.css.erb), then helpers like <code>asset_path</code> and <code>asset_data_uri</code> are available in your CSS rules.</p>
    		<pre class="delayed">
#logo { 
  background: url(<&#37;= asset_data_uri 'logo.png' &#37;>); 
}
    		</pre>
    	</section>
    	
    	<section class="slide">
    		<h2>CSS</h2>
    		<p>The generated code is like so:</p>
    		<pre>
#logo { background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAABkCAMAAACxdeD+AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccl
  0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/CSSIiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1
  sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4
  gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIge
  G1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9
  Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNSBNYWNpbnRvc2gi
  IHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6ODVBQkU5NzQ1NjU1MTFFMUFGODdFNTI1QzQwQzYzNkMiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6ODVBQkU5NzU1NjU
  1MTFFMUFGODdFNTI1QzQwQzYzNkMiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDowQjAyREI0RDU2NEUxMUUxQUY4N0U1MjVDNDBDNjM2
  QyIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDowQjAyREI0RTU2NEUxMUUxQUY4N0U1MjVDNDBDNjM2QyIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6e
  G1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pvv5YQwAAACEUExURcvLy/Pz87CwsImJic/Pz/v7++Tk5K+vr62trd3d3YCAgLGxsaKiot/f38rKyri4uPf398fHx/Dw8Pj4+LW1
  tenp6ZaWlqurq66uroODg8jIyIuLi5ycnIqKiu/v7/r6+oWFhZubm9jY2KampuHh4ZiYmNLS0tnZ2YSEhH9/f7Kysv///3IN8QsAAACqSURBVHja7NXnDoIwFAXgikXcey/cem7f//
  2sDV3E8EdRY3qTNvTLpaeEEJh4Uizgn2L/clxucziZAlgdPIzXaA8SbIYu1nCOhZiDuXhFIuduk1xsIHr0L2YKO0zVGHueihNxhXXoulXMOSOD1XLRpu8s8hZl1Rv9+tuUh3yls4zb
  P7bnd4NC+vvSySAZVGs76U55rYfdU3+v5AXlLEv3rfiJKPw7CvAuwAAQmUbpoWRiDAAAAABJRU5ErkJggg==);
}
    		</pre>
    	</section>
    	
    	<section class="slide">
    		<h2>Things to keep in mind!</h2>
    		<p class="delayed">Most browsers support base-64 encoding (IE8+), and IE6 and 7 can be tricked but do not support it natively.</p>
    		<p class="delayed">Base-64 encoded images are larger than the original file (by a third), but if you have multiple base-64 images in a stylesheet and then GZip the sheet, the overall gains of less HTTP-requests and GZip acting over multiple files combined will far outweigh the size gain converting to base-64. On this site, it’s the difference between 80 KB of CSS + images, and 22.8 KB for one CSS file with the images inside.</p>

        <p class="delayed">Because of the increase in data size with base-64, it is vital that you optimize the images you are converting as much as possible—every single byte counts. Combine ImageOptim, PNGNQ, base-64 encoding and GZip and you will defy the very Interwebz Gods with your insane levels of compression.</p>
    	</section>
    
    </section>
    
    <section>
      <header class="slide">
      	<h1>Thank you!</h1>
      </header>
    </section>
    
  </div>
  <div class="clear"></div>
</div>
 <!-- End of Main Section -->

<%= render partial: "shared/slideshow-js" %>